---
title: "Advent of Code"
subtitle: "My solutions and notes"
#description: "My solutions and notes for Advent of Code."
code-tools: false
---

[Advent of Code](https://adventofcode.com) is a series of increasingly difficult programming challenges, 
released daily each year throughout December in the run-up to Christmas.

This website is created from the  [EllaKaye/advent-of-code-website-template](https://github.com/EllaKaye/advent-of-code-website-template) template repository. 
There's documentation on how to use and adapt the template in the repo README.

It is built with [Quarto](https://quarto.org) and works hand-in-hand with the R package [**aochelpers**](https://github.com/EllaKaye/aochelpers). 
The package provides function to manage this website, e.g. to create new posts from a template, 
to download and read in the puzzle input, 
and will eventually include functions to help with the challenges themselves. See the [package website](https://ellakaye.github.io/aochelpers/) for more details.

As part of the demo, this template comes with an example listing page and Day 1 post for 2022, which you can delete with `aochelpers::aoc_delete_year(2022)`, as well as a listing and introduction to get started for 2023.

There are two built-in themes. The light theme is designed to be quite clean, with a Christmas green and red colours. The dark theme is designed to be reminiscent of the Advent of Code website (though not identical, since the design of <https://adventofcode.com> is part of its registered trademark). You can switch between them using the toggle in the top right corner of the page. Both themes use [fonts from iA](https://github.com/iaolo/iA-Fonts). The themes can be adapted in the `custom-light.scss` and `custom-dark.scss` files.



